// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Curry from "bs-platform/lib/es6/curry.js";

console.log(/* array */[
          1,
          2,
          3
        ].map((function (a) {
              return a + 1 | 0;
            })).filter((function (a) {
            return a % 2 === 0;
          })));

var v = Path.join("a", "b", "c");

console.log(v);

function add(x, y, z) {
  return (x + y | 0) + z | 0;
}

var six = add(1, 2, 3);

setTimeout((function (param) {
        console.log("----- KAREL");
        return /* () */0;
      }), 5000);

console.log(Path.dirname("../"));

var add$1 = (
  function(a, b) {
    console.log("hello from raw JavaScript!");
    return a + b
  }
);

function f (a,b){
  return a + b
};

console.log(Curry._2(add$1, 1, 2));

console.log(f(2, 3));

var match = typeof __filename === "undefined" ? undefined : __filename;

if (match !== undefined) {
  console.log(match);
} else {
  console.log("non-node environment");
}

var karel = {
  name: "Karel"
};

var pepa = {
  name: "Pepa"
};

console.log(karel.name);


  function draw(x, y, border) {
    console.log(x, y, border)
  }

;

draw(10, 10, undefined);

var el = document.getElementById("root");

console.log(el);

function make(param) {
  console.log("experiment");
  return /* () */0;
}

export {
  v ,
  six ,
  add$1 as add,
  f ,
  karel ,
  pepa ,
  el ,
  make ,
  
}
/*  Not a pure module */
