/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const CountDownBS = require('./CountDown.bs');

import {reactElement as ReasonReact_reactElement} from '../src/React.shim';

export const $$default: <T1>(_1:{
  readonly interval: number; 
  readonly onFinished: ((_1:void) => T1); 
  readonly run: boolean
}) => ReasonReact_reactElement = function CountDown<T1>(Arg1: any) {
  const result = CountDownBS.default({interval:Arg1.interval, onFinished:function (Arg11: any) {
      const result1 = Arg1.onFinished(Arg11);
      return result1
    }, run:Arg1.run});
  return result
};

export default $$default;
