// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as UseCountDown$ReactTemplate from "./UseCountDown.bs.js";

function n(x) {
  return String(x);
}

function CountDown(Props) {
  var interval = Props.interval;
  var run = Props.run;
  var onFinished = Props.onFinished;
  var timeToLaunch = UseCountDown$ReactTemplate.$$default(interval, run, onFinished);
  return React.createElement("div", {
              className: "countdown"
            }, String(timeToLaunch));
}

var make = CountDown;

var $$default = CountDown;

export {
  n ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
