/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const Falcon9BS = require('./Falcon9.bs');

import {reactElement as ReasonReact_reactElement} from '../src/React.shim';

export const make: <className>(_1:{ readonly className: className }) => ReasonReact_reactElement = Falcon9BS.make;
