// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Fire$ReactTemplate from "./Fire.bs.js";
import * as Rocket$ReactTemplate from "./Rocket.bs.js";
import * as Payload$ReactTemplate from "./Payload.bs.js";

function Falcon9(Props) {
  var launch = Props.launch;
  var launchClass = launch ? "launched" : "";
  return React.createElement("div", {
              className: "rocket " + (String(launchClass) + "")
            }, React.createElement(Payload$ReactTemplate.make, { }), React.createElement(Rocket$ReactTemplate.make, { }), React.createElement(Fire$ReactTemplate.make, { }));
}

var make = Falcon9;

var $$default = Falcon9;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
