/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Falcon9BS = require('./Falcon9.bs');

import {reactElement as ReasonReact_reactElement} from '../src/React.shim';

export const $$default: (_1:{ readonly launch: boolean }) => ReasonReact_reactElement = Falcon9BS.default;

export default $$default;
