// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FireGen from "./Fire.gen";
import * as RocketGen from "./Rocket.gen";
import * as PayloadGen from "./Payload.gen";

function Falcon9(Props) {
  var className = Props.className;
  return React.createElement("div", {
              className: "rocket " + (String(className) + "")
            }, React.createElement(PayloadGen.make, { }), React.createElement(RocketGen.make, { }), React.createElement(FireGen.make, { }));
}

var make = Falcon9;

export {
  make ,
  
}
/* react Not a pure module */
