/* TypeScript file generated by genType. */

import {blah as blahNotChecked} from './Blah.tsx';

// In case of type error, check the type of 'blah' in 'Index.re' and './Blah.tsx'.
export const blahTypeChecked: React_componentLike<{ readonly text: string },React_element> = blahNotChecked;

// Export 'blah' early to allow circular import from the '.bs.js' file.
export const blah: unknown = blahTypeChecked as React_componentLike<{ readonly text: string },React_element>;

import {componentLike as React_componentLike} from '../src/React.shim';

import {element as React_element} from '../src/React.shim';
