// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as IndexGen from "./Index.gen";

var TSApp = /* module */[];

ReactDOMRe.renderToElementWithId(React.createElement(IndexGen.make, {
          title: "App"
        }), "root");

export {
  TSApp ,
  
}
/*  Not a pure module */
