// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as IndexGen from "./Index.gen";
import * as GlobalStyles$ReactTemplate from "./GlobalStyles.bs.js";

var Mxxx = /* module */[];

ReactDOMRe.renderToElementWithId(React.createElement(IndexGen.blah, {
          text: "Karel"
        }), "root");

export {
  Mxxx ,
  
}
/*  Not a pure module */
