// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as IndexGen from "./Index.gen";

var make = IndexGen.make;

var TSApp = /* module */[/* make */make];

ReactDOMRe.renderToElementWithId(React.createElement(make, {
          title: "App"
        }), "root");

export {
  TSApp ,
  
}
/* make Not a pure module */
