/* TypeScript file generated by genType. */

import {default as makeNotChecked} from './TSApp';

// In case of type error, check the type of 'make' in 'Index.re' and './TSApp'.
export const makeTypeChecked: React_componentLike<{ readonly title: string },React_element> = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make: unknown = makeTypeChecked as React_componentLike<{ readonly title: string },React_element>;

import {componentLike as React_componentLike} from '../src/React.shim';

import {element as React_element} from '../src/React.shim';
