/* TypeScript file generated by genType. */

import {Popup as popupNotChecked} from 'react-leaflet';

// In case of type error, check the type of 'popup' in 'Leaflet.re' and 'react-leaflet'.
export const popupTypeChecked: React_componentLike<{ readonly children: React_element },React_element> = popupNotChecked;

// Export 'popup' early to allow circular import from the '.bs.js' file.
export const popup: unknown = popupTypeChecked as React_componentLike<{ readonly children: React_element },React_element>;

import {componentLike as React_componentLike} from '../src/React.shim';

import {element as React_element} from '../src/React.shim';
