// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as UseMessageToast$ReactTemplate from "./UseMessageToast.bs.js";

function s(prim) {
  return prim;
}

function MessageToast(Props) {
  var header = Props.header;
  var match = UseMessageToast$ReactTemplate.hook(/* () */0);
  var addMessage = match[1];
  return React.createElement("div", undefined, React.createElement("h2", undefined, header), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(addMessage, new Date().toString());
                    })
                }, "Add Message"), React.createElement("ul", undefined, Belt_Array.map(match[0], (function (message) {
                        return React.createElement("li", undefined, message[/* text */1]);
                      }))));
}

var make = MessageToast;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
