/* TypeScript file generated by genType. */

import {default as makeNotChecked} from './TSRocket';

// In case of type error, check the type of 'make' in 'Rocket.re' and './TSRocket'.
export const makeTypeChecked: React_componentLike<{},React_element> = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make: unknown = makeTypeChecked as React_componentLike<{},React_element>;

// tslint:disable-next-line:no-var-requires
const RocketBS = require('./Rocket.bs');

import {componentLike as React_componentLike} from '../src/React.shim';

import {element as React_element} from '../src/React.shim';

export const ts: React_componentLike<{},React_element> = RocketBS.ts;
