/* TypeScript file generated by genType. */
/* eslint-disable import/first */


import {default as makeNotChecked} from './TSRocket';

// In case of type error, check the type of 'make' in 'Rocket.re' and './TSRocket'.
export const makeTypeChecked: (_1:{}) => React_element = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make: unknown = makeTypeChecked as (_1:{}) => React_element;

// tslint:disable-next-line:no-var-requires
const RocketBS = require('./Rocket.bs');

import {element as React_element} from '../src/React.shim';

export const $$default: (_1:{}) => React_element = RocketBS.default;

export default $$default;
