// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

var mapClass = Emotion.css(undefined, /* :: */[
      Emotion.width(/* `pct */[
            5591841,
            100
          ]),
      /* :: */[
        Emotion.height(/* `px */[
              25096,
              300
            ]),
        /* [] */0
      ]
    ]);

export {
  mapClass ,
  
}
/* mapClass Not a pure module */
