/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const UseCountDownBS = require('./UseCountDown.bs');

export const $$default: <T1>(_1:number, _2:boolean, _3:((_1:void) => T1)) => number = function <T1>(Arg1: any, Arg2: any, Arg3: any) {
  const result = Curry._3(UseCountDownBS.default, Arg1, Arg2, function (Arg11: any) {
      const result1 = Arg3(Arg11);
      return result1
    });
  return result
};

export default $$default;
