// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function useState(prim) {
  return React.useState((function () {
                return Curry._1(prim, /* () */0);
              }));
}

function useEffect2(prim, prim$1) {
  React.useEffect((function () {
          return Curry._1(prim, /* () */0);
        }), prim$1);
  return /* () */0;
}

function $$setTimeout$1(prim, prim$1) {
  return setTimeout(prim, prim$1);
}

function $$clearTimeout$1(prim) {
  clearTimeout(prim);
  return /* () */0;
}

function decrement(x) {
  return x - 1 | 0;
}

function $$default(interval, run, onFinished) {
  var match = React.useState((function () {
          return interval;
        }));
  var setTimeToLaunch = match[1];
  var timeToLaunch = match[0];
  useEffect2((function (param) {
          if (run) {
            if (timeToLaunch > 0) {
              var timerId = setTimeout((function (param) {
                      return Curry._1(setTimeToLaunch, decrement);
                    }), 1000);
              return (function (param) {
                        clearTimeout(timerId);
                        return /* () */0;
                      });
            } else {
              Curry._1(onFinished, /* () */0);
              return undefined;
            }
          }
          
        }), /* tuple */[
        timeToLaunch,
        run
      ]);
  return timeToLaunch;
}

export {
  useState ,
  useEffect2 ,
  $$setTimeout$1 as $$setTimeout,
  $$clearTimeout$1 as $$clearTimeout,
  decrement ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
