/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const WorldMapBS = require('./WorldMap.bs');

import {reactElement as ReasonReact_reactElement} from '../src/React.shim';

export const make: (_1:{ readonly header: string }) => ReasonReact_reactElement = WorldMapBS.make;
